<a href="https://colab.research.google.com/github/raisaurav797-svg/Workshop/blob/main/Workshop6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1: Create a 2D ndarray of type Integer, e.g., �
1 2 3
4 5 6
7 8 9
� and see its properties

In [ ]:
import numpy as np
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print("Shape:",ar.shape)
print("Data type:", ar.dtype)
print("Dimensions:",ar.ndim)
print("Size:",ar.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Data type: int64
Dimensions: 2
Size: 9


 Construct a diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4]

In [ ]:
ar=np.diag([1,2,3,4])
print(ar)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Problem 6: Construct a matrix of shape (4,5) with whatever elements, and then slice it to obtain
a matrix of shape (3,3) that contains only upper-left portion of the original matrix.

In [ ]:
A=np.arange(20).reshape(4,5)
print("Original Matrix:\n",A)
B = A[:3,:3]
print("Sliced Matrix:\n",B)

Original Matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Sliced Matrix:
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


Problem 1: Create two matrices 𝑨𝑨 = �
1 2 3
4 5 6
7 8 9
� and 𝑩𝑩 = �1 1 1
2 2 2�. Add them together. What
do you observe? Give the explanation behind it.

In [ ]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[1,1,1],[2,2,2]])
print(A+B)

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

To sum any two matrices both needs to have same shape

Problem 3: Given two compatible matrices, write a Python function that performs Matrix-Matrix
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-
Matrix product.

In [ ]:
def matrix_matrix_product(A,B):
    res=np.zeros((len(A),len(B[0])))
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                res[i][j]+= A[i][k]*B[k][j]
    return res
A = np.array([[2,4],[4,5]])
B = np.array([[5,9],[3,8]])
print(matrix_matrix_product(A, B))
print(np.dot(A, B))

[[22. 50.]
 [35. 76.]]
[[22 50]
 [35 76]]


Problem 4: Given a matrix, write a Python function that checks if it is a symmetric matrix.

In [ ]:
def is_symmetric(A):
    return np.array_equal(A,A.T)
A=np.array([[1,2,3],[2,5,6],[3,6,9]])
print(is_symmetric(A))

True
